import re

# Lee tu archivo actual
with open('network_discovery_tool/output.py', 'r') as f:
    content = f.read()

# Nuevo código para generate_html_report (el que te pasé)
new_html_function = '''def generate_html_report(results: List[Dict], port_info: Optional[Dict], service_scan: bool) -> str:
    """Genera un reporte HTML visual."""
    # Template como string simple (sin saltos de línea problemáticos)
    html_template = '''<!DOCTYPE html>
<html>
<head>
    <title>Network Scan Report</title>
    <meta charset="UTF-8">
    <style>
        body { 
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; 
            margin: 20px; 
            background-color: #f5f5f5;
            color: #333;
        }
        .container {
            max-width: 1200px;
            margin: 0 auto;
            background: white;
            padding: 30px;
            border-radius: 10px;
            box-shadow: 0 0 20px rgba(0,0,0,0.1);
        }
        h1 { 
            color: #2c3e50; 
            border-bottom: 3px solid #3498db;
            padding-bottom: 10px;
        }
        .stats {
            background: #ecf0f1;
            padding: 15px;
            border-radius: 5px;
            margin: 20px 0;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
        }
        th {
            background-color: #3498db;
            color: white;
            padding: 12px;
            text-align: left;
        }
        td {
            padding: 10px;
            border-bottom: 1px solid #ddd;
        }
        tr:hover {
            background-color: #f9f9f9;
        }
        .host-up { background-color: #d4edda; }
        .port-badge {
            display: inline-block;
            background: #2ecc71;
            color: white;
            padding: 3px 8px;
            border-radius: 12px;
            margin: 2px;
            font-size: 12px;
        }
        .service-badge {
            display: inline-block;
            background: #3498db;
            color: white;
            padding: 3px 8px;
            border-radius: 12px;
            margin: 2px;
            font-size: 12px;
        }
        .timestamp {
            color: #7f8c8d;
            font-style: italic;
        }
        .no-ports { color: #95a5a6; font-style: italic; }
    </style>
</head>
<body>
    <div class="container">
        <h1>🔍 Network Scan Report</h1>
        <p class="timestamp">Generated: {timestamp}</p>
        
        <div class="stats">
            <h3>📊 Scan Statistics</h3>
            <p><strong>Hosts Found:</strong> {host_count}</p>
            {port_stats}
        </div>
        
        <h2>🎯 Active Hosts</h2>
        <table>
            <tr>
                <th>IP Address</th>
                <th>Hostname</th>
                <th>Response Time</th>
                <th>Open Ports</th>
                {service_th}
            </tr>
            {rows}
        </table>
        
        <div class="timestamp">
            <p>Generated by Network Discovery Tool v0.2.0</p>
        </div>
    </div>
</body>
</html>'''
    
    # Preparar estadísticas de puertos
    port_stats = ""
    if port_info:
        total_open_ports = sum(len(ports) for ports in port_info.values())
        hosts_with_ports = sum(1 for ports in port_info.values() if ports)
        port_stats = f'''
        <p><strong>Open Ports Found:</strong> {total_open_ports}</p>
        <p><strong>Hosts with open ports:</strong> {hosts_with_ports}/{len(results)}</p>
        '''
    
    # Preparar filas de la tabla
    rows = ""
    service_th = '<th>Services</th>' if service_scan else ''
    
    for host in sorted(results, key=lambda x: x['ip']):
        # Puertos como badges
        ports_html = ""
        services_html = ""
        
        if port_info and host['ip'] in port_info:
            ports = port_info[host['ip']]
            if ports:
                ports_html = '<br>'.join([
                    f'<span class="port-badge">{p["port"]}/TCP</span>' 
                    for p in ports
                ])
                
                if service_scan:
                    services_html = '<br>'.join([
                        f'<span class="service-badge">{p["service"]}</span>' 
                        for p in ports
                    ])
            else:
                ports_html = '<span class="no-ports">None</span>'
        
        rows += f'''
        <tr class="host-up">
            <td><strong>{host['ip']}</strong></td>
            <td>{host['hostname']}</td>
            <td>{host['response_time']} ms</td>
            <td>{ports_html}</td>
            {f'<td>{services_html}</td>' if service_scan else ''}
        </tr>
        '''
    
    return html_template.format(
        timestamp=datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
        host_count=len(results),
        port_stats=port_stats,
        service_th=service_th,
        rows=rows
    )'''

# Patrón para encontrar generate_html_report y todo su contenido
# Busca desde "def generate_html_report" hasta que encuentre otra "def " o el final
pattern = r'def generate_html_report\(.*?\):.*?(?=\n\s*def |\Z)'

# Reemplaza solo esa función
new_content = re.sub(pattern, new_html_function, content, flags=re.DOTALL)

# Guarda el archivo
with open('network_discovery_tool/output.py', 'w') as f:
    f.write(new_content)

print("✅ Función generate_html_report reemplazada exitosamente")
print("✅ Otras funciones (generate_report, generate_text_report) preservadas")
